{% set name = "iso8601" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/iso8601-{{ version }}.tar.gz
  sha256: 6b1d3829ee8921c4301998c909f7829fa9ed3cbdac0d3b16af2d743aed1ba8df

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.6,<4

test:
  imports:
    - iso8601
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/micktwomey/pyiso8601
  license: MIT
  license_file: LICENSE
  summary: Simple module to parse ISO 8601 dates
  doc_url: http://pyiso8601.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - JamesMakela-NOAA
    - ocefpaf
