{% set name = "iso8601" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/iso8601-{{ version }}.tar.gz
  sha256: 79ec9749f8bf35ffae77f835e80e96d2f95affa0f79d3d7b25c0fa7e06207a8b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - iso8601
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/micktwomey/pyiso8601
  license: MIT
  license_file: LICENSE
  summary: Simple module to parse ISO 8601 dates
  doc_url: http://pyiso8601.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - JamesMakela-NOAA
    - ocefpaf
