{% set version = "0.1.15" %}

package:
  name: iso8601
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/iso8601/iso8601-{{ version }}.tar.gz
  sha256: 1e38c6638d4b10d9ca86531425e0a5a2afd1f3061ebdf85a8ebb1dff24e48fe8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - iso8601

about:
  home: https://github.com/micktwomey/pyiso8601
  license: MIT
  license_file: LICENSE
  summary: Simple module to parse ISO 8601 dates
  doc_url: http://pyiso8601.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - JamesMakela-NOAA
    - ocefpaf
