{% set version = "0.1.16" %}

package:
  name: iso8601
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/iso8601/iso8601-{{ version }}.tar.gz
  sha256: 36532f77cc800594e8f16641edae7f1baf7932f05d8e508545b95fc53c6dc85b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - iso8601

about:
  home: https://github.com/micktwomey/pyiso8601
  license: MIT
  license_file: LICENSE
  summary: Simple module to parse ISO 8601 dates
  doc_url: http://pyiso8601.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - JamesMakela-NOAA
    - ocefpaf
