{% set name = "iso8601" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/iso8601-{{ version }}.tar.gz
  sha256: 32811e7b81deee2063ea6d2e94f8819a86d1f3811e49d23623a41fa832bef03f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6,<4
    - pip
    - poetry
  run:
    - python >=3.6,<4

test:
  imports:
    - iso8601
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/micktwomey/pyiso8601
  license: MIT
  license_file: LICENSE
  summary: Simple module to parse ISO 8601 dates
  doc_url: http://pyiso8601.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - JamesMakela-NOAA
    - ocefpaf
